"""Generator module producing ExportScene.cs and ValidateScene.cs C# Unity Editor tools."""
import logging
from pathlib import Path

logger = logging.getLogger(__name__)


class CSharpToolsGenerator:
    """Generates ExportScene.cs and ValidateScene.cs C# Unity Editor scripts."""

    def __init__(self, output_dir: Path | str):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_export_scene_script(self) -> Path:
        """Generates ExportScene.cs C# script for exporting open scene to scene_export.json."""
        code = """// Auto-generated Unity Scene Exporter Tool
// Generated by recoverytool pipeline
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

public static class ExportScene
{
    [MenuItem("Tools/Export Current Scene")]
    public static void ExportOpenSceneToJson()
    {
        Debug.Log("Exporting current Unity scene to scene_export.json...");

        List<Dictionary<string, object>> rootList = new List<Dictionary<string, object>>();
        GameObject[] rootObjs = UnityEngine.SceneManagement.SceneManager.GetActiveScene().GetRootGameObjects();

        foreach (GameObject rootObj in rootObjs)
        {
            rootList.Add(SerializeGameObject(rootObj));
        }

        Dictionary<string, object> exportData = new Dictionary<string, object>
        {
            { "version", "1.0.0" },
            { "root_objects", rootList }
        };

        string json = EditorJsonUtility.ToJson(exportData, true);
        string outputPath = Path.Combine(Application.dataPath, "../recoverytool/database/scene_export.json");
        File.WriteAllText(outputPath, json);
        Debug.Log($"Scene exported successfully to: {outputPath}");
    }

    private static Dictionary<string, object> SerializeGameObject(GameObject go)
    {
        Dictionary<string, object> data = new Dictionary<string, object>
        {
            { "path_id", go.GetInstanceID() },
            { "name", go.name },
            { "active", go.activeSelf },
            { "layer", go.layer },
            { "tag", go.tag }
        };

        // Transform
        Transform t = go.transform;
        Dictionary<string, object> tData = new Dictionary<string, object>
        {
            { "position", new Dictionary<string, float> { { "x", t.localPosition.x }, { "y", t.localPosition.y }, { "z", t.localPosition.z } } },
            { "rotation", new Dictionary<string, float> { { "x", t.localRotation.x }, { "y", t.localRotation.y }, { "z", t.localRotation.z }, { "w", t.localRotation.w } } },
            { "scale", new Dictionary<string, float> { { "x", t.localScale.x }, { "y", t.localScale.y }, { "z", t.localScale.z } } }
        };
        data["transform"] = tData;

        // Components
        List<Dictionary<string, object>> compList = new List<Dictionary<string, object>>();
        Component[] comps = go.GetComponents<Component>();
        foreach (Component c in comps)
        {
            if (c == null) continue;
            compList.Add(new Dictionary<string, object>
            {
                { "type_name", c.GetType().Name },
                { "name", c.name }
            });
        }
        data["components"] = compList;

        // Children
        List<Dictionary<string, object>> childList = new List<Dictionary<string, object>>();
        for (int i = 0; i < t.childCount; i++)
        {
            childList.Add(SerializeGameObject(t.GetChild(i).gameObject));
        }
        data["children"] = childList;

        return data;
    }
}
"""
        out_path = self.output_dir / "ExportScene.cs"
        out_path.write_text(code, encoding="utf-8")
        return out_path

    def generate_validate_scene_script(self) -> Path:
        """Generates ValidateScene.cs C# script for Unity Editor runtime validation."""
        code = """// Auto-generated Unity Scene Validation Tool
// Generated by recoverytool pipeline
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

public static class ValidateScene
{
    [MenuItem("Tools/Validate Recovered Scene")]
    public static void ValidateRecoveredScene()
    {
        Debug.Log("Starting Unity Editor Runtime Validation...");
        int missingMeshes = 0;
        int missingMaterials = 0;
        int brokenRefs = 0;
        int missingScripts = 0;

        GameObject[] allObjects = Object.FindObjectsOfType<GameObject>();

        foreach (GameObject go in allObjects)
        {
            MeshFilter mf = go.GetComponent<MeshFilter>();
            if (mf != null && mf.sharedMesh == null) missingMeshes++;

            Renderer rend = go.GetComponent<Renderer>();
            if (rend != null && (rend.sharedMaterials == null || rend.sharedMaterials.Length == 0)) missingMaterials++;

            Component[] comps = go.GetComponents<Component>();
            foreach (Component c in comps)
            {
                if (c == null) missingScripts++;
            }
        }

        Debug.Log($"[Validation Summary] GameObjects: {allObjects.Length}, Missing Meshes: {missingMeshes}, Missing Materials: {missingMaterials}, Missing Scripts: {missingScripts}");

        string reportPath = Path.Combine(Application.dataPath, "../recoverytool/reports/validation_runtime.md");
        string reportText = $"# Unity Runtime Validation Report\\n\\n" +
            $"- Total GameObjects Inspected: {allObjects.Length}\\n" +
            $"- Missing Meshes: {missingMeshes}\\n" +
            $"- Missing Materials: {missingMaterials}\\n" +
            $"- Missing Scripts/Null Components: {missingScripts}\\n";

        File.WriteAllText(reportPath, reportText);
        Debug.Log($"Runtime validation report written to: {reportPath}");
    }
}
"""
        out_path = self.output_dir / "ValidateScene.cs"
        out_path.write_text(code, encoding="utf-8")
        return out_path
